### ISSUE TITLE
Closing asyncpg pool hangs when closing bot from terminal

### ISSUE THREAD

**Issue by cyrus01337** [DuckBot-Discord/DuckBot#34]
### Summary
When closing Duckbot via Ctrl+C in the terminal, asyncpg hangs with the following error message:
```sh
[2023-02-21 09:29:26,920|WARNING|asyncpg.pool._warn_on_long_close:927] Pool.close() is taking over 60 seconds to complete. Check if you have any unreleased connections left. Use asyncio.wait_for() to set a timeout for Pool.close().
```

### Problem
Application hangs on shutdown, which ends up becoming unachievable.

### Expected
The bot shuts down successfully, gracefully, when instructed via terminal.

### Specifications
**Python:** 3.11.2
**OS:** Ubuntu 22.10

### Additional Info
Have not tried this by shutting down the bot from a `shutdown` command _if one exists_.

**Comment by LeoCx1000** [comment]
Fixed as of aa4b6c7985a7c8b5739447d7dd54acc0457d8dfc.

The issue was that a background task (waiting for timers) was using a `safe_connection` and keeping it open as it waited for new timers.

When the bot closed, said task got cancelled but since the pool was already closed, rolling back the transaction that the `safe_connection` initialized made it hang.
